config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :students, :controllers => {:omniauth_callbacks => "students/omniauth_callbacks"}
  devise_for :professionals, :controllers => { :registrations => "registrations" }
  resources :visits

  root to: 'application#index'
  
  authenticated :professional do
    scope module: :professional do
      resource :profile, except: :index, as: 'my_profile'
    end
  end

  authenticated :student do
    scope module: :student do
      resources :profile, only: [] do
        member do
          get :send_email, to: 'profiles#send_email'
          post :favorite, to: 'profile_favorites#create'
          delete :favorite, to: 'profile_favorites#destroy'
        end
      end
      get :favorites, to: 'favorites#index'
    end
  end

  authenticated :admin do
    scope module: :admin do
      resources :profiles, only: [:show, :edit, :update] do
        collection do
          get :unverified, to: 'profiles#unverified'
        end
        member do
          post :verify, to: 'profiles#verify'
          post :unverify, to: 'profiles#unverify'
        end
      end
    end
  end

  resources :profiles, only: [:index, :show], constraints: { id: /\d+/ }
  
  get :about, to: 'application#about'
  get :sign_up_gate, to: 'application#sign_up_gate', as: :sign_up_gate
  get :sign_in_gate, to: 'application#sign_in_gate', as: :sign_in_gate
  get :map, to: 'profiles#map'
  get :search, to: 'search#search'
  get :visits, to: 'visits#index'

end  

app/models/profile.rb
require 'elasticsearch/model'
# The Profile class is responsible for creating professional profiles that detail the information of each professional
class Profile < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :professional
  belongs_to :sector
  has_many :visits, dependent: :destroy

  validates_presence_of :name, message: "- Please provide your name"
  validates_presence_of :job, message: "- Please select your profession"

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  geocoded_by :address
  after_validation :geocode

  # Fields for the search
  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name, analyzer: 'english'
      indexes :full_description, analyzer: 'english'
      indexes :info, analyzer: 'english'
      indexes :company, analyzer: 'english'
      indexes :req_quals, analyzer: 'english'
      indexes :req_skills, analyzer: 'english'
      indexes :address, analyzer: 'english'
      indexes :job, analyzer: 'english'
    end
  end

  # for retrievieng the image absolute url
  def image_url
      image.url(:medium)
  end

  # Actual search method -  using fields above
  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name', 'full_description', 'info', 'company', 'req_quals', 'req_skills', 'address', 'job']
          }
        }
      }
      )
  end

end

#  Deleting prev profile indexes (for elastic)
Profile.__elasticsearch__.client.indices.delete index: Profile.index_name rescue nil

# recreate profile indexes
Profile.__elasticsearch__.client.indices.create index: Profile.index_name, body: { settings: Profile.settings.to_hash, mappings: Profile.mappings.to_hash }

# for auto-sync model with elastic search
Profile.import

app/controllers/admin/profiles_controller.rb
# The Admin Profiles Controller is responsible for allowing an admin user to verify profiles
class Admin::ProfilesController < ProfilesBaseController

  before_action :authenticate_admin!

  def unverified
    @profiles = Profile.where(:verified=>[false, nil])
  end

  def verify
    @profile = Profile.find(params[:id])
    @profile.verified = true
    @profile.save
    redirect_to unverified_profiles_path
  end

  def unverify
    @profile = Profile.find(params[:id])
    @profile.verified = false
    @profile.save
    redirect_to :back
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end


end

app/controllers/professional/profiles_controller.rb
# The Professional Profile Controller is responsible for allowing a professional to create, update and delete a profile

class Professional::ProfilesController < ProfilesBaseController

  before_action :authenticate_professional!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.verified = false
    @profile.professional = current_professional
    if @profile.save 
      redirect_to root_path
    else
      render :action=>'new'
    end
  end

  def show
    @profile = current_professional.profile
    render "/profiles/show"
  end

  def edit
    @profile = current_professional.profile
  end

  def update
    @profile = current_professional.profile
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  def destroy
    @profile = current_professional.profile
    @profile.destroy
    redirect_to '/'
    flash[:notice] = "Your profile has been deleted successfully"
  end

end

app/controllers/profiles_controller.rb
# The Profiles Controller is responsible for showing all of the professionals profiles to users who are not yet signed in

class ProfilesController < ProfilesBaseController

  def index
    @profiles = Profile.where(:verified=>true)
    @result = @profiles.paginate(:page => params[:page], :per_page => 3).select([:id, :name, :company, :info, :job, :image_file_name, :sector_id])
    @hash = find_markers(@profiles)
    respond
  end

  def respond
    respond_to do |format|
      format.html { 
       }
       format.json {
         render :json => @result.as_json( :methods => [:image_url])  
       }
    end
  end

  def show
    allow_only_verified_profile
    @hash = find_markers(@profile)
    @visit = Visit.new
  end

  def allow_only_verified_profile
    possible_profile = Profile.find(params[:id])
    if possible_profile.verified
      @profile = possible_profile
    else
      redirect_to '/'
      flash[:notice] = "This profile has not yet been verified"
    end
  end 

end

app/controllers/student/profiles_controller.rb
#The Student Profiles Controller is responsible for allowing students to send emails via the profile pages
class Student::ProfilesController < ProfilesBaseController

  before_action :authenticate_student!
  
  def send_email
    @profile = Profile.find(params[:id])
    @professional = Professional.find(@profile.professional_id)
    @student = current_student
    post_email(@professional, @student)
    redirect_to profile_path(@profile.id)
  end

  private

  def post_email(professional, student)
    StudentMailer.intro_email(professional, student).deliver_now
    flash[:notice] = "Your email has been sent."
  end

end

app/helpers/profile_helper.rb
module ProfileHelper

	def profile_verified
    possible_profile = Profile.find(params[:id])
    if possible_profile.verified
      @profile = possible_profile
    else
      redirect_to '/'
      flash[:notice] = "This profile has not yet been verified"
    end
  end  

  def find_marker(profile)
    @hash = Gmaps4rails.build_markers(profile) do |profile, marker|
      marker.lat profile.latitude
      marker.lng profile.longitude
      marker.title profile.name
    end
  end

  def find_all_markers
    @profiles = Profile.where(:verified=>true)
    @hash = Gmaps4rails.build_markers(@profiles) do |profile, marker|
      marker.lat profile.latitude
      marker.lng profile.longitude
      marker.title profile.name
    end
  end

	def profile_params
    params.require(:profile).permit(:name, :professional_id, :sector_id, :image, :info, :company, :full_description, :address, :verified,
      :job, :motivation, :suitability, :academic_back, :req_quals, :req_skills, :expectations)
  end
end

app/views/profiles/index.html.erb
<% content_for :script do %>
	<script>$(document).ready(buildMap);</script>
<% end %>
<column class="col-sacrificial1 span_1_of_16"></column>

<column class="col short span_14_of_16">

<div style='width: 100%;'>
    <div id="map" class="profiles_map" ></div>
</div>

<grid>
  <div class="container">
	  <% @profiles.each do |profile| %>
	    <section class="new-card-form">
		    <a href="/profiles/<%= profile.id %>" id="profile_link"><h5> <%= image_tag profile.image.url(:thumb) %> </h5></a>
		    <h5> <%= profile.name %>, <span class="sub"><%= profile.company %> </span></h5>
		   
		    <p> <%= profile.info %> </p>
	    </section>
	  <% end %>
  </div>
</grid>

</column>

<column class="col-sacrificial1 span_1_of_16"></column>
<script>
	function buildMap() {
	  var handler = Gmaps.build('Google');
	  handler.buildMap({ internal: {id: 'map'}}, function(){
	    markers = handler.addMarkers(<%= raw @hash.to_json %>);
	    handler.bounds.extendWith(markers);
	    // handler.getMap().setZoom(15); 
	    handler.fitMapToBounds();
	  });
	};
</script>

app/views/profiles/map.html.erb
<!-- <% content_for :script do %>
	<script>$(document).ready(buildMap);</script>
<% end %>
<column class="col-sacrificial1 span_1_of_16"></column>
<div style='width: 100%;'>
    <div id="map" class="span_14_of_16" style='height: 400px;'></div>
</div>
<column class="col-sacrificial1 span_1_of_16"></column>
<script>
function buildMap() {
  var handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
};
</script> -->

app/views/profiles/show.html.erb
<% content_for :script do %>
	<script>$(document).ready(buildMap);</script>
<% end %>


<!-- New profile page -->
<column class="col-sacrificial1 span_1_of_16">
</column>
<column class="col-sacrificial1 span_1_of_16">
</column>

<column class="col-sacrificial span_5_of_16 ">
		

	<profile id="profile-image--sector" class="vertical_align">
		<map id="google_map" class="">
      <div class="individual-map">
        <div id="map" class="profiles_map jsHandle"></div>
      </div>
    </map>
		<%= image_tag @profile.sector.image.url(:medium), :class=>"profile_sector_image landscape"%>
	</profile>
</column>
<column class="col-sacrificial span_7_of_16 ">
	<profile id="profile-text--individual" class="vertical_align dark">

		<summaryHead class="profile-thumb">
			<%= image_tag @profile.image.url(:thumb), :class=>"profile_sector_image"%>
		</summaryHead>
	  <summaryHead class="headline_info professional_info">
	    <h3>
	    	<%= @profile.job %>, <span class="sub"><%= @profile.name %></span>
	    </h3>
	    <h5>
	    	<%= @profile.company %> 	
	    </h5>
	    <spacer class="small line"></spacer>
	    <h5 class="sub highlight" id="jsLocationButton">
	    		Located at: <%= @profile.address %>
	    </h5>
	  </summaryHead>

	  <spacer class="small"></spacer>

	  <content class="profile-full_info">
	    <h5>Summary: </h5>
	    <p><%= @profile.info %></p>
	    <spacer class="tiny"></spacer>
	    <h5>More about the day: </h5>
	    <p><%= @profile.full_description %></p>
	    <spacer class="tiny"></spacer>
	    <h5>What you can expect on your day with us: </h5>
	    <p><%= @profile.expectations %></p>
	    <spacer class="tiny"></spacer>
	    <h5>People in my profession require the following qualifications (not necessary for your one day experience): </h5>
	    <p><%= @profile.req_quals %></p>
	    <spacer class="tiny"></spacer>
	    <h5>People in my profession, often have the following skills: </h5>
	    <p><%= @profile.req_skills %></p>
	  </content>

			<section class="email sub highlight">
        <% if current_student %>
          <%= link_to "Register Interest", send_email_profile_path(@profile), data:{confirm: "We are about to send an email to #{@profile.name}, registering your interest in a day of work experience with him/her. \n\nThe email will include your name and email address so that they are able to contact you. \n\nPlease confirm that you wish to send this email"}, :class=>"email_links"%>
          <!-- Adding this profile to favortes -->
          <%- unless current_student.favorite_profiles.exists?(@profile.id) -%>
                    <%= link_to 'Add to favorites', favorite_profile_path(@profile), method: :post %>
                <%- else -%>
                    <%= link_to 'Remove from favorites', favorite_profile_path(@profile), method: :delete, :class => "profile_links"  %>
                <%- end -%>
        <% else %>
          <h5>Please <%= link_to "sign in", new_student_session_path %> to contact <%= @profile.name %></h5>
        <% end %>
      </section>
      <section class="edit">
        <% if current_professional == @profile.professional %>
          <%= link_to "Edit Profile", edit_my_profile_path %>
          <a href="/visits/<%= @profile.id %>">See my visits</a>
                <a href='#' class="delete_profile_confirmation">Delete Profile</a>
          <%= link_to "", my_profile_path, method: :delete, :class=>"delete_profile"%>
        <% end %>
      </section>



	</profile>	

</column>

<script>
function buildMap() {
  var handler = Gmaps.build('Google', { scrollwheel: false, zoomControl:   false });
  handler.buildMap({ internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15); 
  });
};
</script>

  

app/views/profiles/verification.html.erb
<column class="col-sacrificial1 span_1_of_16"></column>

<grid>
  <div class="container">
    <% @profiles.each do |profile| %>
      <section class="new-card-form span_4_of_16">
        <a href="/profiles/<%= profile.id %>"><h5> <%= image_tag profile.image.url(:thumb) %> </h5></a>
        <h5> <%= profile.name %> </h5>
        <h5> <%= profile.company %> </h5>
        <h5> <%= profile.info %> </h5>
        <%= link_to 'Verify', verify_path(id: profile.id), method: :post %>
      </section>
    <% end %>
  </div>
</grid>