config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :students, :controllers => {:omniauth_callbacks => "students/omniauth_callbacks"}
  devise_for :professionals, :controllers => { :registrations => "registrations" }
  resources :visits

  root to: 'application#index'
  
  authenticated :professional do
    scope module: :professional do
      resource :profile, except: :index, as: 'my_profile'
    end
  end

  authenticated :student do
    scope module: :student do
      resources :profile, only: [] do
        member do
          get :send_email, to: 'profiles#send_email'
          post :favorite, to: 'profile_favorites#create'
          delete :favorite, to: 'profile_favorites#destroy'
        end
      end
      get :favorites, to: 'favorites#index'
    end
  end

  authenticated :admin do
    scope module: :admin do
      resources :profiles, only: [:show, :edit, :update] do
        collection do
          get :unverified, to: 'profiles#unverified'
        end
        member do
          post :verify, to: 'profiles#verify'
          post :unverify, to: 'profiles#unverify'
        end
      end
    end
  end

  resources :profiles, only: [:index, :show], constraints: { id: /\d+/ }
  
  get :about, to: 'application#about'
  get :sign_up_gate, to: 'application#sign_up_gate', as: :sign_up_gate
  get :sign_in_gate, to: 'application#sign_in_gate', as: :sign_in_gate
  get :map, to: 'profiles#map'
  get :search, to: 'search#search'
  get :visits, to: 'visits#index'

end  

app/models/profile.rb
require 'elasticsearch/model'
# The Profile class is responsible for creating professional profiles that detail the information of each professional
class Profile < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :professional
  belongs_to :sector
  has_many :visits, dependent: :destroy

  validates_presence_of :name, message: "- Please provide your name"
  validates_presence_of :job, message: "- Please select your profession"

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  geocoded_by :address
  after_validation :geocode

  # Fields for the search
  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name, analyzer: 'english'
      indexes :full_description, analyzer: 'english'
      indexes :info, analyzer: 'english'
      indexes :company, analyzer: 'english'
      indexes :req_quals, analyzer: 'english'
      indexes :req_skills, analyzer: 'english'
      indexes :address, analyzer: 'english'
      indexes :job, analyzer: 'english'
    end
  end

  # for retrievieng the image absolute url
  def image_url
      image.url(:medium)
  end

  # Actual search method -  using fields above
  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name', 'full_description', 'info', 'company', 'req_quals', 'req_skills', 'address', 'job']
          }
        }
      }
      )
  end

end

#  Deleting prev profile indexes (for elastic)
Profile.__elasticsearch__.client.indices.delete index: Profile.index_name rescue nil

# recreate profile indexes
Profile.__elasticsearch__.client.indices.create index: Profile.index_name, body: { settings: Profile.settings.to_hash, mappings: Profile.mappings.to_hash }

# for auto-sync model with elastic search
Profile.import

app/controllers/admin/profiles_controller.rb
# The Admin Profiles Controller is responsible for allowing an admin user to verify profiles
class Admin::ProfilesController < ProfilesBaseController

  before_action :authenticate_admin!

  def unverified
    @profiles = Profile.where(:verified=>[false, nil])
  end

  def verify
    @profile = Profile.find(params[:id])
    @profile.verified = true
    @profile.save
    redirect_to unverified_profiles_path
  end

  def unverify
    @profile = Profile.find(params[:id])
    @profile.verified = false
    @profile.save
    redirect_to :back
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end


end

app/controllers/professional/profiles_controller.rb
# The Professional Profile Controller is responsible for allowing a professional to create, update and delete a profile

class Professional::ProfilesController < ProfilesBaseController

  before_action :authenticate_professional!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.verified = false
    @profile.professional = current_professional
    if @profile.save 
      redirect_to root_path
    else
      render :action=>'new'
    end
  end

  def show
    @profile = current_professional.profile
    render "/profiles/show"
  end

  def edit
    @profile = current_professional.profile
  end

  def update
    @profile = current_professional.profile
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  def destroy
    @profile = current_professional.profile
    @profile.destroy
    redirect_to '/'
    flash[:notice] = "Your profile has been deleted successfully"
  end

end

app/controllers/profiles_controller.rb
# The Profiles Controller is responsible for showing all of the professionals profiles to users who are not yet signed in

class ProfilesController < ProfilesBaseController

  def index
    @profiles = Profile.where(:verified=>true)
    @result = @profiles.paginate(:page => params[:page], :per_page => 3).select([:id, :name, :company, :info, :job, :image_file_name, :sector_id])
    @hash = find_markers(@profiles)
    respond
  end

  def respond
    respond_to do |format|
      format.html { 
       }
       format.json {
         render :json => @result.as_json( :methods => [:image_url])  
       }
    end
  end

  def show
    allow_only_verified_profile
    @hash = find_markers(@profile)
    @visit = Visit.new
  end

  def allow_only_verified_profile
    possible_profile = Profile.find(params[:id])
    if possible_profile.verified
      @profile = possible_profile
    else
      redirect_to '/'
      flash[:notice] = "This profile has not yet been verified"
    end
  end 

end

app/controllers/student/profiles_controller.rb
#The Student Profiles Controller is responsible for allowing students to send emails via the profile pages
class Student::ProfilesController < ProfilesBaseController

  before_action :authenticate_student!
  
  def send_email
    @profile = Profile.find(params[:id])
    @professional = Professional.find(@profile.professional_id)
    @student = current_student
    post_email(@professional, @student)
    redirect_to profile_path(@profile.id)
  end

  private

  def post_email(professional, student)
    StudentMailer.intro_email(professional, student).deliver_now
    flash[:notice] = "Your email has been sent."
  end

end

app/helpers/profile_helper.rb
module ProfileHelper

	def profile_verified
    possible_profile = Profile.find(params[:id])
    if possible_profile.verified
      @profile = possible_profile
    else
      redirect_to '/'
      flash[:notice] = "This profile has not yet been verified"
    end
  end  

  def find_marker(profile)
    @hash = Gmaps4rails.build_markers(profile) do |profile, marker|
      marker.lat profile.latitude
      marker.lng profile.longitude
      marker.title profile.name
    end
  end

  def find_all_markers
    @profiles = Profile.where(:verified=>true)
    @hash = Gmaps4rails.build_markers(@profiles) do |profile, marker|
      marker.lat profile.latitude
      marker.lng profile.longitude
      marker.title profile.name
    end
  end

	def profile_params
    params.require(:profile).permit(:name, :professional_id, :sector_id, :image, :info, :company, :full_description, :address, :verified,
      :job, :motivation, :suitability, :academic_back, :req_quals, :req_skills, :expectations)
  end
end

app/views/admin/profiles/edit.html.erb
<section class="col-sacrificial span_1_of_16"></section>
<section class="col-sacrificial span_1_of_16"></section>

<section class="col span_13_of_16">
<% if @profile.errors.any? %>
  <div class="" id="error_explanation">
    <h4><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h4>
 
    <ul>
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<section class="profile_form">
  
  <%= form_for @profile, url: "/profiles/#{@profile.id}", html: {multipart: true} do |f| %>
        <br>
  <%= f.file_field :image %><br><br>
  <section class="col span_7_of_16">
      <h5><%= f.label :name%></h5>
      <%= f.text_field :name, id:'text_box_sm', cols:10, rows: 2   %><br>
      <h5><%= f.label :sector%></h5>
      <%= f.collection_select :sector_id, Sector.order(:name),:id,:name, include_blank: true %>
      <h5><%= f.label :job %></h5>
      <%= f.text_field :job, id:'text_box_sm', cols:10, rows: 2 %><br>
      <h5><%= f.label :company %></h5>
      <%= f.text_field :company, id:'text_box_sm', cols: 10, rows: 10 %><br><br>
      <h5><%= f.label :address %></h5>
      <%= f.text_area :address, id:'text_box_sm', cols: 10, rows: 10 %><br><br>
      <br>
      <br>
      <br>
      <h5><%= f.label "Please provide details of your Academic Background" %></h5>
      <%= f.text_area :academic_back, id:'text_box_md', cols: 10, rows: 10 %><br><br>
      <h5><%= f.label "Are there any required qualifications for your role?" %></h5>
      <%= f.text_area :req_quals, id:'text_box_md', cols: 10, rows: 10 %><br><br>
      <h5><%= f.label "What skills are required in this role?" %></h5>
      <%= f.text_area :req_skills, id:'text_box_md', cols: 10, rows: 10 %>
    </section>
    <section class="col-sacrificial1 span_1_of_16"></section>
    <section class="col-sacrificial2 span_1_of_16"></section>
    <section class="col span_7_of_16">
      <h5><%= f.label "What motivates you to offer a one day experience?" %></h5>
      <%= f.text_area :motivation, id:'text_box_md', cols: 10, rows: 10 %><br><br>
      <h5><%= f.label "What do you think makes you suitable as a mentor for young people looking for a one day experience?" %></h5>
      <%= f.text_area :suitability, id:'text_box_md', cols: 10, rows: 10 %><br><br>
      <h5><%= f.label "What can a young person expect from one day in your role" %></h5>
      <%= f.text_area :expectations, id:'text_box_md', cols: 10, rows: 10 %><br><br>
      <h5><%= f.label "Please provide a paragraph or two describing, more fully, the one day experience on offer" %></h5>
      <%= f.text_area :full_description, id:'text_box_lg', cols: 10, rows: 10 %>
      <br>
      <br>
      <br>
      <%= f.submit %>
    </section>
    
  <% end %>
</section>
</section>
<section class="col-sacrificial span_1_of_16"></section>

app/views/admin/profiles/show.html.erb
<tag id="darkPage"><tag>

<column class="col-sacrificial span_1_of_16 dark">
</column>

<column class="col--profile-image span_5_of_16 dark">
  <feature class="photo_field vertical_align">
    <div align="middle" id="photo-field-link">
      <%= image_tag @profile.image.url(:medium) %>
    </div>
  </feature>
</column>

<column class="col-sacrificial span_10_of_16 ">
  <section class="feature-description vertical_align fixed-height">
    <summaryHead class="professional_info">
      <h4><%= @profile.name %></h4>
      <h5>
        <%= @profile.company %>
        <span class="sub">
          Located at: <%= @profile.address %>
        </span>
      </h5>
    </summaryHead>
    <content class="profile-full_info">
      <em>Summary: </em>
      <p><%= @profile.info %></p>
      <em>More about the day: </em></br>
      <p><%= @profile.full_description %></p>
      <em>What you can expect on your day with us: </em></br>
      <p><%= @profile.expectations %></p>
      <em>Required qualifications: </em><br>
      <p><%= @profile.req_quals %></p>
      <em>Required skills: </em></br>
      <p><%= @profile.req_skills %></p>
      <em>Academic background: </em></br>
      <p><%= @profile.academic_back %></p>
      <em>Motivations: </em></br>
      <p><%= @profile.motivation %></p>
      <em>Suitability: </em></br>
      <p><%= @profile.suitability %></p>
      
    </content>
 
    <section class="edit">
      <% if @profile.verified == false %>
        <ul><%= link_to 'Verify', verify_profile_path(id: @profile.id), method: :post %></ul>
      <% else %>
        <ul><%= link_to "Unverify", unverify_profile_path(id: @profile.id), method: :post%></ul>
      <% end %>
        <ul><%= link_to "Edit", edit_profile_path %></ul>
        
    </section>
  </section>
</column>

<section class="profile_container">
  

app/views/admin/profiles/unverified.html.erb
<column class="col-sacrificial1 span_1_of_16"></column>

<grid>
  <div class="container">
    <% @profiles.each do |profile| %>
      <section class="new-card-form span_4_of_16">
        <a href="/profiles/<%= profile.id %>" id="profile_link"><h5> <%= image_tag profile.image.url(:thumb) %> </h5></a>
        <h5> <%= profile.name %> </h5>
        <h5> <%= profile.company %> </h5>
        <h5> <%= profile.info %> </h5>
        <%= link_to 'Verify', verify_profile_path(id: profile.id), method: :post %>
      </section>
    <% end %>
  </div>
</grid>