config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :students, :controllers => {:omniauth_callbacks => "students/omniauth_callbacks"}
  devise_for :professionals, :controllers => { :registrations => "registrations" }
  resources :visits

  root to: 'application#index'
  
  authenticated :professional do
    scope module: :professional do
      resource :profile, except: :index, as: 'my_profile'
    end
  end

  authenticated :student do
    scope module: :student do
      resources :profile, only: [] do
        member do
          get :send_email, to: 'profiles#send_email'
          post :favorite, to: 'profile_favorites#create'
          delete :favorite, to: 'profile_favorites#destroy'
        end
      end
      get :favorites, to: 'favorites#index'
    end
  end

  authenticated :admin do
    scope module: :admin do
      resources :profiles, only: [:show, :edit, :update] do
        collection do
          get :unverified, to: 'profiles#unverified'
        end
        member do
          post :verify, to: 'profiles#verify'
          post :unverify, to: 'profiles#unverify'
        end
      end
    end
  end

  resources :profiles, only: [:index, :show], constraints: { id: /\d+/ }
  
  get :about, to: 'application#about'
  get :sign_up_gate, to: 'application#sign_up_gate', as: :sign_up_gate
  get :sign_in_gate, to: 'application#sign_in_gate', as: :sign_in_gate
  get :map, to: 'profiles#map'
  get :search, to: 'search#search'
  get :visits, to: 'visits#index'

end  

app/views/shared/_unsignedinicons.html.erb
<a href='/' >
<icon class="icons jsicons" >
	<img class="icon" src="/images/icons/arrow-button-13.svg">
	<p class="links">Home</p>
</icon>
</a>

<%= link_to about_path do%>
	<icon id="about-icon" class="icons jsicons" >
		<img class="icon" src="/images/icons/iconography-15.svg"/>
		<p class="links">About</p>
	</icon>
<% end %>

<% if !professional_signed_in? && !student_signed_in? && !admin_signed_in? %>
	<%= link_to sign_in_gate_path do%>
		<icon id="how-wide" class="icons--signin jsicons" >
			<img class="icon" src="/images/icons/iconography-05.svg"/>
			<p class="links">Sign in</p>
		</icon>
	<% end %>
<% end %>

<% if professional_signed_in? || student_signed_in? || admin_signed_in? %>
	<%= link_to destroy_professional_session_path, method: :delete do%>
		<icon id="professional_sign_out" class="icons jsicons" >
			<img class="icon" src="/images/icons/iconography-09.svg">
			<p class="links">Sign out</p>
		</icon>
	<% end %>
<% end %>

<% if student_signed_in? %>
	<%= link_to favorites_path do%>
		<icon id="favorites-icon" class="icons jsicons" >
			<img class="icon" src="/images/icons/icons-01.svg"/>
			<p class="links">Favorites</p>
		</icon>
	<% end %>
<% end %>


<%= link_to search_path do%>
	<icon id="search-icon" class="icons jsicons" >
		<img class="icon" src="/images/icons/iconography-07.svg"/>
		<p class="links">Search</p>
	</icon>
<% end %>

<%= link_to profiles_path do%>
	<icon id="browse-profiles-icon" class="icons jsicons" >
		<img class="icon" src="/images/icons/iconography-06.svg"/>
		<p class="links">Browse Profiles</p>
	</icon>
<% end %>