config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :students, :controllers => {:omniauth_callbacks => "students/omniauth_callbacks"}
  devise_for :professionals, :controllers => { :registrations => "registrations" }
  resources :visits

  root to: 'application#index'
  
  authenticated :professional do
    scope module: :professional do
      resource :profile, except: :index, as: 'my_profile'
    end
  end

  authenticated :student do
    scope module: :student do
      resources :profile, only: [] do
        member do
          get :send_email, to: 'profiles#send_email'
          post :favorite, to: 'profile_favorites#create'
          delete :favorite, to: 'profile_favorites#destroy'
        end
      end
      get :favorites, to: 'favorites#index'
    end
  end

  authenticated :admin do
    scope module: :admin do
      resources :profiles, only: [:show, :edit, :update] do
        collection do
          get :unverified, to: 'profiles#unverified'
        end
        member do
          post :verify, to: 'profiles#verify'
          post :unverify, to: 'profiles#unverify'
        end
      end
    end
  end

  resources :profiles, only: [:index, :show], constraints: { id: /\d+/ }
  
  get :about, to: 'application#about'
  get :sign_up_gate, to: 'application#sign_up_gate', as: :sign_up_gate
  get :sign_in_gate, to: 'application#sign_in_gate', as: :sign_in_gate
  get :map, to: 'profiles#map'
  get :search, to: 'search#search'
  get :visits, to: 'visits#index'

end  

app/controllers/application_controller.rb
# The Application Controller is responsible for determining the route taken after sign in
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @profile = Profile.first
  end

  def after_sign_in_path_for(resource)
    if current_professional
      my_profile_path
    elsif current_admin
      unverified_profiles_path
    else
      root_path
    end
  end

  def about
  end

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:sign_up) << :profession_id
 end

end

app/views/application/about.html.erb
<!-- Cols in place for positioning purposes -->
<section class="col-sacrificial1 span_1_of_16"></section>
<section class="col-sacrificial1 span_1_of_16"></section>
<section class="col-sacrificial1 span_1_of_16"></section>


<body>
<!-- Center field - site image -->
  <section class="col-center span_10_of_16" id="main">


    <spacer class="small"></spacer>
    <feature class="photo_field ">
      <img align="middle" src="/images/OneDayExperience.jpg" id="site-img" />
    </feature>
    <spacer class="small"></spacer>
    <h3 style="text-align:center">· Tell me and I'll forget · <br> · Show me and I'll remember · <br> · Involve me and I'll understand ·</h3>
    <spacer class="small"></spacer>
    <h2>The One Day Experience</h2>

    <spacer class="small"></spacer>

    <h4>
    One Day Experience provides a platform connecting young people with professionals willing to offer one day, on the job, experience in their sector. 
    </h4>

    <spacer class="small"></spacer>
    <h4>
    One Day experience will help young people make more informed choices about which career to embark upon.
    </h4>

    <spacer class="large"></spacer>

    <h2>Why should I get involved?</h2>

    <spacer class="small"></spacer>

    <h4>
    Young people will have the opportunity to discover what a given job really entails, and the route through which the professional reached their job. The experience will also help widen the young person's network.
    </h4> 

    <spacer class="small"></spacer>

    <h4>
    Professionals are given the opportunity to share their passions, and to support and inspire the young people in their community.
    </h4>
    
    <spacer class="small"></spacer>
    
    <h4>
    They are also afforded the opportunity to get to know passionate young people who are interested in their field of work, and who might become their colleagues in the future.... One Day.
    </h4>

    <spacer class="large"></spacer>

  </section>
<!-- End of center field -->
</body>

<!-- Cols in place for positioning purposes -->
<section class="col-sacrificial1 span_1_of_16"></section>
<section class="col-sacrificial1 span_1_of_16"></section>
<section class="col-sacrificial1 span_1_of_16"></section>

app/views/application/index.html.erb
	<!-- Cols in place for positioning purposes -->
	<column class="col-sacrificial1 span_1_of_16"></column>
	<column class="col-sacrificial1 span_1_of_16"></column>
	<column class="col-sacrificial2 span_1_of_16"></column>


	<!-- Button for previous -->
	<column  class="col-left-circle span_2_of_16">
		
		<circle id="left-circle" class="navigation-circle">
		<a href="#">

			<svg version="1.1" id="left-circle-img" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 		width="269.83px" height="269.831px" viewBox="0 0 269.83 269.831" enable-background="new 0 0 269.83 269.831"
	 		xml:space="preserve">
				<circle id="svg-circle" fill="none" stroke="#6ABEDB" stroke-width="3" stroke-miterlimit="10" cx="135.406" cy="134.381" r="116.653"/>
				<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="114" y1="135.3662" x2="176.3564" y2="135.3662">
					<stop  offset="0" style="stop-color:#6ABEDB"/>
					<stop  offset="1" style="stop-color:#96CCDB"/>
				</linearGradient>
				<polygon fill="url(#SVGID_1_)" points="114,171.367 176.356,135.365 114,99.364 "/>
			</svg>
			
		</a>
		</circle>

	</column>
	<column class="col-sacrificial2 span_1_of_16">
	</column>

	<!-- Center field - profile image and buttons -->
	<column class="col-center span_4_of_16">
		<feature class="photo_field vertical_align">

			<a href="#" id="photo-field-link">
				
				<description id="index-feature-job-description">
					
					<text class="text-summary">	
						<p>1 day in the life of the</p>				
						<h5 id="buddy-job"></h5>
					</text>
				</description>

				<img align="middle" src="/images/grey.png" id="field-img" alt="Image not found" onError="this.src='/images/medium/missing.png';"/>

				<description id="index-feature-description">
					<img class='profile-img' id='profile-pic'>
					<text class="text-summary">
						<h5 id="buddy-name"><span id="buddy-company"></span></h5>
						<p id="buddy-info"></p>
					</text>
				</description>

			</a>

		</feature>
	</column>
	<!-- End of center field -->

	<!-- Button for next -->
	<column class="col-sacrificial2 span_1_of_16"></column>
	<column class="col-sacrificial span_2_of_16">
		<circle id="right-circle" class="navigation-circle">

			<a href='#'>
				<svg version="1.1" id="right-circle-img" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
		 		width="269.83px" height="269.831px" viewBox="0 0 269.83 269.831" enable-background="new 0 0 269.83 269.831"
		 		xml:space="preserve">
					<circle id="svg-circle-right" fill="none" stroke="#6ABEDB" stroke-width="3" stroke-miterlimit="10" cx="135.406" cy="134.381" r="116.653"/>
					<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="114" y1="135.3662" x2="176.3564" y2="135.3662">
						<stop  offset="0" style="stop-color:#6ABEDB"/>
						<stop  offset="1" style="stop-color:#96CCDB"/>
					</linearGradient>
					<polygon fill="url(#SVGID_1_)" points="114,171.367 176.356,135.365 114,99.364 "/>
				</svg>
			</a>

		</circle>
	</column>

	<!-- Cols in place for positioning purposes -->

	<column class="col-sacrificial2 span_1_of_16"></column>
	<column class="col-sacrificial1 span_1_of_16"></column>
	<column class="col-sacrificial1 span_1_of_16"></column>

app/views/application/sign_in_gate.html.erb
<column class="col-sacrificial1 span_1_of_16"></column>
<column class="col-sacrificial1 span_1_of_16"></column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col span_4_of_16">

	<box class="box vertical_align underline">
		<%= link_to new_professional_session_path do%>
				<p class="sign-links">Professional Sign in</p>
		<% end %>
	</box>
	<box class="box vertical_align">
		<%= link_to new_professional_registration_path do%>
				<p class="sign-links">Sign Up As A Professional</p>
		<% end %>
	</box>
</column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col span_4_of_16">

	<box class="box vertical_align underline">
		<%= link_to new_student_session_path do%>	
			<p class="sign-links">Student Sign in</p>	
		<% end %>
	</box>
	<box class="box vertical_align">
		<%= link_to new_student_registration_path do %>
			<p class="sign-links">Sign Up As A Student</p>
		<% end %>
	</box>	

</column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col-sacrificial1 span_1_of_16"></column>
<column class="col-sacrificial1 span_1_of_16"></column>



</column>

app/views/application/sign_up_gate.html.erb
<column class="col-sacrificial1 span_1_of_16"></column>
<column class="col-sacrificial1 span_1_of_16"></column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col span_4_of_16" style="background-color:red;">
<%= link_to new_professional_registration_path do%>
		<p class="sign_up_links">Sign Up As A Professional</p>
<% end %>

</column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col span_4_of_16" style="background-color:red;">

<%= link_to new_student_registration_path do %>
		<p class="sign_up_links">Sign Up As A Student</p>
<% end %>
</column>
<column class="col-sacrificial2 span_1_of_16"></column>
<column class="col-sacrificial1 span_1_of_16"></column>
<column class="col-sacrificial1 span_1_of_16"></column>